# List the VSCode extensions you want to be installed
vscode:
  extensions:
    - https://github.com/Mackaber/vscode-jupytext/releases/download/v0.1.2/vscode-jupytext-0.1.2.vsix  # Jupytext
    - ms-python.python
    - ms-toolsai.jupyter

tasks:
  - name: Setup Python and Poetry
    init: |
      # Ensure that the desired Python version is installed
      pyenv install -f 3.10.13
      pyenv global 3.10.13
      pyenv rehash

      # Install Poetry
      pip install poetry
    command: |
      poetry install