# List the VSCode extensions you want to be installed
vscode:
  extensions:
    - https://github.com/Mackaber/vscode-jupytext/releases/download/v0.1.2/vscode-jupytext-0.1.2.vsix  # Jupytext
    - ms-python.python
    - ms-toolsai.jupyter

tasks:
  - name: Install Python 3.10.13
    init: |
      if ! pyenv versions | grep -q 3.10.13; then
        pyenv install 3.10.13
      fi
      pyenv global 3.10.13
    command: python --version
  - name: Setup Poetry environment
    init: |
      pip install poetry
    command: poetry install