# List the VSCode extensions you want to be installed
vscode:
  extensions:
    - https://github.com/Mackaber/vscode-jupytext/releases/download/v0.1.2/vscode-jupytext-0.1.2.vsix  # Jupytext
    - ms-python.python
    - ms-toolsai.jupyter

tasks:
  - name: Setup Python and Poetry
    init: |
      # Ensure that the desired Python version is installed
      pyenv global system
      pyenv rehash

      # Install psycopg2 dependencies 
      sudo apt -y install libpq-dev python3-dev

      # Install Poetry
      pip3 install poetry
    command: |
      poetry install